spring.application.name=frontendpractice
server.port=8888

# DB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/frontendpractice
spring.datasource.username=root
spring.datasource.password=1234

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.shinhan.frontendpractice.dto
mybatis.configuration.map-underscore-to-camel-case=true
